// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:user_app/secrets.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: firebaseApiKeyWeb,
    appId: appIdWebWindows,
    messagingSenderId: messagingSenderId,
    projectId: 'app-warehouse-55797',
    authDomain: 'app-warehouse-55797.firebaseapp.com',
    storageBucket: 'app-warehouse-55797.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: firebaseApiKeyAndroid,
    appId: apiIdAndroid,
    messagingSenderId: messagingSenderId,
    projectId: 'app-warehouse-55797',
    storageBucket: 'app-warehouse-55797.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: firebaseApiKeyOS,
    appId: apiIdOS,
    messagingSenderId: messagingSenderId,
    projectId: 'app-warehouse-55797',
    storageBucket: 'app-warehouse-55797.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: firebaseApiKeyOS,
    appId: apiIdOS,
    messagingSenderId: messagingSenderId,
    projectId: 'app-warehouse-55797',
    storageBucket: 'app-warehouse-55797.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: firebaseApiKeyWindows,
    appId: appIdWebWindows,
    messagingSenderId: messagingSenderId,
    projectId: 'app-warehouse-55797',
    authDomain: 'app-warehouse-55797.firebaseapp.com',
    storageBucket: 'app-warehouse-55797.firebasestorage.app',
  );

}